spring:
  application:
    name: example-middleware
server:
  port: 8082
cqrs:
  naming:
    prefix: middleware-demo
  context:
    enabled: true
    auto-correlation-id: true
    mdc-keys:
      - correlationId
      - tenantId
logging:
  level:
    com.borjaglez.cqrs.example.middleware: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{correlationId:-no-cid}] [%X{tenantId:-no-tenant}] %-5level %logger{36} - %msg%n"
