spring:
  application:
    name: example-rabbitmq
  docker:
    compose:
      file: examples/example-rabbitmq/compose.yml
      lifecycle-management: start-and-stop

server:
  port: 8081

cqrs:
  naming:
    prefix: order-service
  rabbitmq:
    enabled: true
    prefix: order-service
    commands:
      exchange: commands
      concurrent-consumers: 5
    events:
      exchange: events
      concurrent-consumers: 5
    queries:
      exchange: queries
      concurrent-consumers: 5
