spring:
  application:
    name: example-outbox
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8082

cqrs:
  naming:
    prefix: example-outbox
  kafka:
    prefix: example-outbox
    commands:
      enabled: false
    queries:
      enabled: false
  jdbc:
    initialize-schema: always
  outbox:
    enabled: true
