spring:
  application:
    name: multi-service-order
  docker:
    compose:
      file: examples/multi-service/order-service/compose.yml
      lifecycle-management: start-and-stop

server:
  port: 8090

cqrs:
  naming:
    prefix: ecommerce
  rabbitmq:
    enabled: true
    prefix: ecommerce
    commands:
      exchange: commands
      concurrent-consumers: 5
    events:
      exchange: events
      concurrent-consumers: 5
    queries:
      exchange: queries
      concurrent-consumers: 5
