CREATE TABLE IF NOT EXISTS ${table} (
  id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id     VARCHAR(64)   NOT NULL UNIQUE,
  event_name   VARCHAR(255)  NOT NULL,
  event_class  VARCHAR(512)  NOT NULL,
  payload      VARBINARY     NOT NULL,
  context      VARBINARY,
  created_at   TIMESTAMP     NOT NULL,
  published_at TIMESTAMP,
  failed_at    TIMESTAMP,
  attempts     INT           NOT NULL DEFAULT 0,
  last_error   VARCHAR(2000)
);
CREATE INDEX IF NOT EXISTS ${index}_pending ON ${table} (published_at, failed_at, id);
