package com.borjaglez.cqrs.jdbc.outbox;

import java.io.IOException;
import java.io.StringWriter;
import java.io.UncheckedIOException;
import java.util.Map;
import java.util.Properties;

import org.springframework.beans.factory.aot.BeanFactoryInitializationAotContribution;
import org.springframework.beans.factory.aot.BeanFactoryInitializationAotProcessor;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;
import org.springframework.core.env.Environment;

import com.borjaglez.cqrs.naming.MessageNamingStrategy;

import lombok.Generated;

/**
 * Writes the outbox name index ({@value OutboxEventTypeResolver#INDEX_LOCATION}) at build time,
 * since a native image cannot scan the classpath for the {@code @CqrsMessage} events of {@code
 * cqrs.aot.message-packages}. The binding hints of those classes come from the core's {@code
 * CqrsMessageTypesAotProcessor}.
 */
public class OutboxEventNamesAotProcessor implements BeanFactoryInitializationAotProcessor {

  @Override
  public BeanFactoryInitializationAotContribution processAheadOfTime(
      ConfigurableListableBeanFactory beanFactory) {
    Environment environment = beanFactory.getBean(Environment.class);
    if (!environment.getProperty("cqrs.outbox.enabled", Boolean.class, false)) {
      return null;
    }
    Map<String, String> names =
        OutboxEventTypeResolver.scan(
            OutboxEventTypeResolver.packages(environment),
            beanFactory.getBean(MessageNamingStrategy.class),
            beanFactory.getBeanClassLoader());
    String content = toProperties(names);
    return (generationContext, code) -> {
      generationContext
          .getGeneratedFiles()
          .addResourceFile(OutboxEventTypeResolver.INDEX_LOCATION, content);
      generationContext
          .getRuntimeHints()
          .resources()
          .registerPattern(OutboxEventTypeResolver.INDEX_LOCATION);
    };
  }

  /** Writing to a {@link StringWriter} never fails; the catch block is excluded from coverage. */
  @Generated
  private static String toProperties(Map<String, String> names) {
    Properties properties = new Properties();
    properties.putAll(names);
    StringWriter writer = new StringWriter();
    try {
      properties.store(writer, "Outbox event names generated by spring-boot-cqrs-jdbc");
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
    return writer.toString();
  }
}
